
#- name: add-lb
#  ec2_elb:
#          state: present
#          ec2_elbs: load-balancer
#          region: us-east-1
#          notice: "{{ ec2_instances }}"
#          instance_id: 
#          - "{{ ec2_instances.id }}"


- name: add-lb
  local_action: ec2_elb
  args:
       instance_id: "{{ item.id }}"
       ec2_elbs:  load-balancer
       state: present
       region: us-east-1 
  with_items: ec2_instances.tagged_instances

- name: add-lb
  shell: " ansible localhost -m ec2_remote_facts -a 'region=us-east-1'   | grep web-inova -A4   | sed 's/\"/ /g' | grep id | awk '{print $3}' "
  register: id

