- name: create security group 
  ec2_group:
                     name: web-inova
                     aws_access_key: "{{ aws_access_key }}"
                     aws_secret_key: "{{aws_secret_key}}"
                     description: example firewall aws rules
                     region: us-east-1 
                     rules:
                             - proto: tcp
                               from_port: 80
                               to_port: 80
                               cidr_ip: 0.0.0.0/0
                             - proto: tcp
                               from_port: 443
                               to_port: 443
                               cidr_ip: 0.0.0.0/0
                             - proto: tcp
                               from_port: 22
                               to_port: 22
                               cidr_ip: 0.0.0.0/0

